### PR TITLE
Fix basicAuth, swapping key and name

### LINKED ISSUE #402: basicAuth secret configuration is backwards
The [BasicAuth section of the API docs](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#basicauth) says that [v1.SecretKeySelector scheme](https://kubernetes.io/docs/api-reference/v1.6/#secretkeyselector-v1-core) from Kubernetes is used. Based on that spec, the `name` is the name of the secret to use, and `key` is the key inside that secret. I specified it accordingly, and my metrics collection kept silently failing with no errors in any of the logs:

```
spec:
  endpoints:
  - basicAuth:
      password:
        name: prometheus-basic-auth
        key: password
      username:
        name: prometheus-basic-auth
        key: username
# ...
```

Then I came across some of the user guide examples, the `name` and `key` fields are actually reversed in prometheus-operator:

https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/basic-auth.md#basic-auth-for-targets

Swapping the key names, everything started working:

```
spec:
  endpoints:
  - basicAuth:
      password:
        key: prometheus-basic-auth
        name: password
      username:
        key: prometheus-basic-auth
        name: username
# ...
```

### PR DESCRIPTION
**Pull request by gianrubio**
**Warning: This is a breaking change!!!**

The `key` and `name` were in a inverse (wrong) order.  Before applying this patch edit your `ServiceMonitor` and swap your `key` and `name` values of `basicAuth`.

fix #402

### CODE REVIEW

**Comment by brancz** [comment]
@coreosbot test this please

**Comment by brancz** [comment]
@archSeer can you confirm that this works? I don't think this is a breaking change, as it does not work as intended, but it does need to be mentioned in release notes.

File: pkg/prometheus/operator.go [hunk 1]
```diff
@@ -902,11 +902,16 @@ func (c *Operator) loadBasicAuthSecrets(mons map[string]*v1alpha1.ServiceMonitor
 					}
 				}
 
-				secrets[fmt.Sprintf("%s/%s/%d", mon.Namespace, mon.Name, i)] =
-					BasicAuthCredentials{
-						username: username,
-						password: password,
-					}
+				if username == "" || password == "" {
```
Comment (brancz) [inline pkg/prometheus/operator.go]: actually I think basic auth can just be a username or password

Comment (gianrubio) [inline pkg/prometheus/operator.go]: Should I change from "or" to "and"?

Comment (brancz) [inline pkg/prometheus/operator.go]: Yes I think that makes more sense. As that sounds like a configuration issue from the administrator using the Prometheus Operator.

Comment (gianrubio) [inline pkg/prometheus/operator.go]: done!

**Comment by brancz** [comment]
@coreosbot test this please

**Comment by brancz** [comment]
lgtm, thanks a lot!
