### PR TITLE
fix alertmanager statefulset being pruned by kubectl

### LINKED ISSUE #3029: Alertmanager statefulset pruned unnecessarily
**What happened?**

When kubectl apply --prune is run against a system deployed with prometheus-operator  the alertmanager stateful set gets pruned every time

**Did you expect to see some different?**

Alertmanager stateful set not pruned

**Anything else we need to know?**:

This is the same issue as https://github.com/coreos/prometheus-operator/issues/2642, but for the alertmanager stateful set instead of the prometheus stateful set.

### PR DESCRIPTION
**Pull request by alexconlin**
kubectl-managed annotations will cause the generated statefulset to be pruned
when the source alertmanager is applied with kubectl apply --prune.

To fix this do not transfer any kubectl.kubernetes.io/ annotations to
the generated statefulset.

This is the same problem as fixed in #2944 but for alertmanager rather than
prometheus.

Fixes #3029

Signed-off-by: Alex Conlin-Oakley <alexconlin@gmail.com>

### CODE REVIEW

File: pkg/alertmanager/statefulset_test.go [hunk 1]
```diff
@@ -53,8 +62,14 @@ func TestStatefulSetLabelingAndAnnotations(t *testing.T) {
 
 	require.NoError(t, err)
 
-	if !reflect.DeepEqual(labels, sset.Labels) || !reflect.DeepEqual(annotations, sset.Annotations) {
-		t.Fatal("Labels or Annotations are not properly being propagated to the StatefulSet")
+	if !reflect.DeepEqual(labels, sset.Labels) {
+		fmt.Println(pretty.Compare(labels, sset.Labels))
```
Comment (simonpasquier) [inline pkg/alertmanager/statefulset_test.go]: `t.Log(pretty.Compare(labels, sset.Labels))` instead

File: pkg/alertmanager/statefulset_test.go [hunk 2]
```diff
@@ -53,8 +62,14 @@ func TestStatefulSetLabelingAndAnnotations(t *testing.T) {
...
+		t.Fatal("Labels are not properly being propagated to the StatefulSet")
+	}
+
+	if !reflect.DeepEqual(expectedAnnotations, sset.Annotations) {
+		fmt.Println(pretty.Compare(expectedAnnotations, sset.Annotations))
```
Comment (simonpasquier) [inline pkg/alertmanager/statefulset_test.go]: same thing
