### PR TITLE
*: fix config reloading when using external urls

### LINKED ISSUE #86: Config reload not working
When using external urls the reload endpoint may differ as it can be prefixed, therefore the reload endpoints are not as expected.

@alexsomesan @fabxc 

Fix is on the way, but needs testing.

### PR DESCRIPTION
**Pull request by brancz**
@alexsomesan @fabxc 

Fixes #86

### CODE REVIEW

File: pkg/alertmanager/statefulset.go [hunk 1]
```diff
@@ -171,7 +184,7 @@ func makeStatefulSetSpec(a *spec.Alertmanager) v1beta1.StatefulSetSpec {
 						Name:  "config-reloader",
 						Image: "jimmidyson/configmap-reload",
 						Args: []string{
-							"-webhook-url=http://localhost:9093/-/reload",
+							fmt.Sprintf("-webhook-url=%s", localReloadURL.String()),
```
Comment (fabxc) [inline pkg/alertmanager/statefulset.go]: No need for `.String()`

**Comment by fabxc** [comment]
👍
