### PR TITLE
Fix for omitting source_labels where they are unnecessary

### LINKED ISSUE #2218: Using `labeldrop` on remoteWrite config breaks Prometheus
**What did you do?**

I supplied a remoteWrite config like so:
```
  remoteWrite:
    - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus"
      writeRelabelConfigs:
        - action: labeldrop
          regex: prometheus
        - action: labeldrop
          regex: prometheus_replica
```

**What did you expect to see?**

I expected this to configure Prometheus' remote write config so that it would drop the existing `prometheus` and `prometheus_replica` labels from metrics that are scraped from another Prometheus.

**What did you see instead? Under which circumstances?**

Under all circumstances, I got this error from Prometheus:

```
Error loading config couldn't load configuration (--config.file=/etc/prometheus/config_out/prometheus.env.yaml): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: labeldrop action requires only 'regex', and no other fields
```

**Environment**

* Prometheus Operator version:

	0.25.0

* Kubernetes version information:

	1.10.6

* Kubernetes cluster kind: 

	KOPS on AWS

### PR DESCRIPTION
**Pull request by alebsack**
I've tried my hand at the go workflow and applied the fix outlined by @ViniciusSouza in https://github.com/coreos/prometheus-operator/issues/2218#issuecomment-449349056

Fixes #2218

### CODE REVIEW

File: pkg/prometheus/promcfg.go [hunk 1]
```diff
@@ -750,8 +750,10 @@ func (cg *configGenerator) generateRemoteWriteConfig(version semver.Version, spe
 		if spec.WriteRelabelConfigs != nil {
 			relabelings := []yaml.MapSlice{}
 			for _, c := range spec.WriteRelabelConfigs {
-				relabeling := yaml.MapSlice{
-					{Key: "source_labels", Value: c.SourceLabels},
+				relabeling := yaml.MapSlice{}
+
+				if c.SourceLabels != "" {
```
Comment (brancz) [inline pkg/prometheus/promcfg.go]: `.SourceLabels` is a slice of strings, not a single string, so this needs to be:


```suggestion
				if len(c.SourceLabels) > 0 {
```

**Comment by alebsack** [comment]
@brancz github made this too easy. 👍

**Comment by brancz** [comment]
Awesome :+1: lgtm
